-- Migration 000: Setup migrations tracking table
-- This is the initial migration that creates a table to track all database migrations

-- Create migrations table to track applied migrations
CREATE TABLE IF NOT EXISTS public.migrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    hash VARCHAR(64),  -- SHA-256 hash of migration content for integrity checking
    applied_by VARCHAR(255)  -- Who or what process applied this migration
);

-- Create index on name for faster lookups
CREATE INDEX IF NOT EXISTS idx_migrations_name ON public.migrations(name);

-- Enable RLS with admin-only access
ALTER TABLE public.migrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access" ON public.migrations
    FOR ALL
    USING (auth.role() = 'service_role');

-- Record this migration in migrations table
INSERT INTO public.migrations (name, applied_at, applied_by) 
VALUES ('000_setup_migrations.sql', CURRENT_TIMESTAMP, 'initial setup')
ON CONFLICT (name) DO NOTHING;

-- Add a comment explaining the table
COMMENT ON TABLE public.migrations IS 'Tracks database migrations that have been applied to manage schema versions';
