import React, { useState } from 'react';
import SignaturePad from './SignaturePad';

/**
 * CP12 Landlord Gas Safety Record
 * Based on Gas Safe Register requirements
 */
const CP12Form = () => {
  const [formData, setFormData] = useState({
    // Landlord Details
    landlordName: '',
    landlordAddress: '',
    landlordPostcode: '',
    landlordPhone: '',
    landlordEmail: '',
    
    // Property Details
    propertyAddress: '',
    propertyPostcode: '',
    tenantName: '',
    tenantEmail: '',
    
    // Engineer Details
    engineerName: '',
    engineerGasSafeId: '',
    companyName: '',
    companyGasSafeId: '',
    
    // Dates
    inspectionDate: new Date().toISOString().split('T')[0],
    nextInspectionDate: '',
    
    // Appliances (array)
    appliances: [createEmptyAppliance()],
  });

  const [engineerSignature, setEngineerSignature] = useState(null);
  const [tenantSignature, setTenantSignature] = useState(null);
  const [showPreview, setShowPreview] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);

  function createEmptyAppliance() {
    return {
      id: Date.now(),
      location: '',
      applianceType: '',
      make: '',
      model: '',
      flueType: '',
      operationPressure: '',
      safetyDevice: '',
      // Checks
      operationOk: null,
      ventilationOk: null,
      fluePipesOk: null,
      flueTerminationOk: null,
      flueFlowOk: null,
      spillageOk: null,
      aevOk: null,
      gasTightnessOk: null,
      // Result
      applianceSafe: null,
      defectsIdentified: '',
      remedialAction: '',
    };
  }

  const updateField = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const updateAppliance = (id, field, value) => {
    setFormData(prev => ({
      ...prev,
      appliances: prev.appliances.map(a => 
        a.id === id ? { ...a, [field]: value } : a
      )
    }));
  };

  const addAppliance = () => {
    setFormData(prev => ({
      ...prev,
      appliances: [...prev.appliances, createEmptyAppliance()]
    }));
  };

  const removeAppliance = (id) => {
    if (formData.appliances.length > 1) {
      setFormData(prev => ({
        ...prev,
        appliances: prev.appliances.filter(a => a.id !== id)
      }));
    }
  };

  const calculateNextInspection = () => {
    const inspection = new Date(formData.inspectionDate);
    inspection.setFullYear(inspection.getFullYear() + 1);
    updateField('nextInspectionDate', inspection.toISOString().split('T')[0]);
  };

  const handleEmail = async () => {
    if (!formData.tenantEmail && !formData.landlordEmail) {
      alert('Please enter an email address');
      return;
    }

    setSending(true);
    
    // For now, create a mailto link with form summary
    // In production, this would call a backend API to generate PDF and send email
    const recipient = formData.tenantEmail || formData.landlordEmail;
    const subject = `CP12 Gas Safety Record - ${formData.propertyAddress}`;
    
    const applianceSummary = formData.appliances.map((a, i) => 
      `\nAppliance ${i + 1}: ${a.applianceType} (${a.make} ${a.model})\n` +
      `Location: ${a.location}\n` +
      `Safe to use: ${a.applianceSafe === true ? 'YES' : a.applianceSafe === false ? 'NO' : 'N/A'}\n` +
      `Defects: ${a.defectsIdentified || 'None'}`
    ).join('\n');

    const body = `
LANDLORD GAS SAFETY RECORD (CP12)

PROPERTY: ${formData.propertyAddress}, ${formData.propertyPostcode}
LANDLORD: ${formData.landlordName}
TENANT: ${formData.tenantName}

INSPECTION DATE: ${formData.inspectionDate}
NEXT INSPECTION DUE: ${formData.nextInspectionDate}

ENGINEER: ${formData.engineerName}
GAS SAFE ID: ${formData.engineerGasSafeId}
COMPANY: ${formData.companyName}

APPLIANCES INSPECTED:
${applianceSummary}

---
This record was generated by BoilerBrain.
A signed copy will be provided separately.
    `.trim();

    window.location.href = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    
    setTimeout(() => {
      setSending(false);
      setSent(true);
    }, 1000);
  };

  const CheckButton = ({ value, onChange, label }) => (
    <button
      type="button"
      onClick={() => onChange(value === null ? true : value === true ? false : null)}
      className={`px-3 py-1.5 rounded text-xs font-medium transition-all ${
        value === true ? 'bg-green-500 text-white' :
        value === false ? 'bg-red-500 text-white' :
        'bg-gray-200 text-gray-600'
      }`}
    >
      {label}: {value === true ? '✓' : value === false ? '✗' : '-'}
    </button>
  );

  return (
    <div className="max-w-4xl mx-auto p-4">
      <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-5 text-white">
          <h1 className="text-2xl font-bold">CP12 Gas Safety Record</h1>
          <p className="text-blue-100 text-sm mt-1">Landlord Gas Safety Record</p>
        </div>

        <div className="p-5 space-y-6">
          {/* Landlord Details */}
          <section>
            <h2 className="text-sm font-semibold text-gray-500 mb-3">LANDLORD DETAILS</h2>
            <div className="grid grid-cols-2 gap-3">
              <input
                type="text"
                placeholder="Landlord Name"
                value={formData.landlordName}
                onChange={(e) => updateField('landlordName', e.target.value)}
                className="col-span-2 px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Address"
                value={formData.landlordAddress}
                onChange={(e) => updateField('landlordAddress', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Postcode"
                value={formData.landlordPostcode}
                onChange={(e) => updateField('landlordPostcode', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="tel"
                placeholder="Phone"
                value={formData.landlordPhone}
                onChange={(e) => updateField('landlordPhone', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="email"
                placeholder="Email"
                value={formData.landlordEmail}
                onChange={(e) => updateField('landlordEmail', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
            </div>
          </section>

          {/* Property Details */}
          <section>
            <h2 className="text-sm font-semibold text-gray-500 mb-3">PROPERTY DETAILS</h2>
            <div className="grid grid-cols-2 gap-3">
              <input
                type="text"
                placeholder="Property Address"
                value={formData.propertyAddress}
                onChange={(e) => updateField('propertyAddress', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Postcode"
                value={formData.propertyPostcode}
                onChange={(e) => updateField('propertyPostcode', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Tenant Name"
                value={formData.tenantName}
                onChange={(e) => updateField('tenantName', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="email"
                placeholder="Tenant Email"
                value={formData.tenantEmail}
                onChange={(e) => updateField('tenantEmail', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
            </div>
          </section>

          {/* Engineer Details */}
          <section>
            <h2 className="text-sm font-semibold text-gray-500 mb-3">ENGINEER DETAILS</h2>
            <div className="grid grid-cols-2 gap-3">
              <input
                type="text"
                placeholder="Engineer Name"
                value={formData.engineerName}
                onChange={(e) => updateField('engineerName', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Gas Safe ID"
                value={formData.engineerGasSafeId}
                onChange={(e) => updateField('engineerGasSafeId', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Company Name"
                value={formData.companyName}
                onChange={(e) => updateField('companyName', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
              <input
                type="text"
                placeholder="Company Gas Safe ID"
                value={formData.companyGasSafeId}
                onChange={(e) => updateField('companyGasSafeId', e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
              />
            </div>
          </section>

          {/* Dates */}
          <section>
            <h2 className="text-sm font-semibold text-gray-500 mb-3">INSPECTION DATES</h2>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs text-gray-500 mb-1">Inspection Date</label>
                <input
                  type="date"
                  value={formData.inspectionDate}
                  onChange={(e) => {
                    updateField('inspectionDate', e.target.value);
                  }}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-500 mb-1">Next Inspection Due</label>
                <div className="flex gap-2">
                  <input
                    type="date"
                    value={formData.nextInspectionDate}
                    onChange={(e) => updateField('nextInspectionDate', e.target.value)}
                    className="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  />
                  <button
                    type="button"
                    onClick={calculateNextInspection}
                    className="px-3 py-2 bg-blue-100 text-blue-700 rounded-lg text-xs font-medium"
                  >
                    +1 Year
                  </button>
                </div>
              </div>
            </div>
          </section>

          {/* Appliances */}
          <section>
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-sm font-semibold text-gray-500">APPLIANCES</h2>
              <button
                type="button"
                onClick={addAppliance}
                className="text-xs text-blue-600 font-medium"
              >
                + Add Appliance
              </button>
            </div>
            
            {formData.appliances.map((appliance, idx) => (
              <div key={appliance.id} className="bg-gray-50 rounded-xl p-4 mb-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm font-medium text-gray-700">Appliance {idx + 1}</span>
                  {formData.appliances.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeAppliance(appliance.id)}
                      className="text-xs text-red-500"
                    >
                      Remove
                    </button>
                  )}
                </div>
                
                {/* Appliance Details */}
                <div className="grid grid-cols-2 gap-2 mb-3">
                  <input
                    type="text"
                    placeholder="Location"
                    value={appliance.location}
                    onChange={(e) => updateAppliance(appliance.id, 'location', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  />
                  <select
                    value={appliance.applianceType}
                    onChange={(e) => updateAppliance(appliance.id, 'applianceType', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white"
                  >
                    <option value="">Type...</option>
                    <option value="Boiler">Boiler</option>
                    <option value="Fire">Gas Fire</option>
                    <option value="Cooker">Cooker</option>
                    <option value="Hob">Hob</option>
                    <option value="Water Heater">Water Heater</option>
                    <option value="Other">Other</option>
                  </select>
                  <input
                    type="text"
                    placeholder="Make"
                    value={appliance.make}
                    onChange={(e) => updateAppliance(appliance.id, 'make', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  />
                  <input
                    type="text"
                    placeholder="Model"
                    value={appliance.model}
                    onChange={(e) => updateAppliance(appliance.id, 'model', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  />
                  <select
                    value={appliance.flueType}
                    onChange={(e) => updateAppliance(appliance.id, 'flueType', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white"
                  >
                    <option value="">Flue Type...</option>
                    <option value="Open Flue">Open Flue</option>
                    <option value="Room Sealed">Room Sealed</option>
                    <option value="Flueless">Flueless</option>
                  </select>
                  <input
                    type="text"
                    placeholder="Operating Pressure (mbar)"
                    value={appliance.operationPressure}
                    onChange={(e) => updateAppliance(appliance.id, 'operationPressure', e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  />
                </div>

                {/* Safety Checks */}
                <div className="mb-3">
                  <label className="block text-xs text-gray-500 mb-2">Safety Checks</label>
                  <div className="flex flex-wrap gap-2">
                    <CheckButton
                      value={appliance.operationOk}
                      onChange={(v) => updateAppliance(appliance.id, 'operationOk', v)}
                      label="Operation"
                    />
                    <CheckButton
                      value={appliance.ventilationOk}
                      onChange={(v) => updateAppliance(appliance.id, 'ventilationOk', v)}
                      label="Vent"
                    />
                    <CheckButton
                      value={appliance.flueFlowOk}
                      onChange={(v) => updateAppliance(appliance.id, 'flueFlowOk', v)}
                      label="Flue Flow"
                    />
                    <CheckButton
                      value={appliance.spillageOk}
                      onChange={(v) => updateAppliance(appliance.id, 'spillageOk', v)}
                      label="Spillage"
                    />
                    <CheckButton
                      value={appliance.gasTightnessOk}
                      onChange={(v) => updateAppliance(appliance.id, 'gasTightnessOk', v)}
                      label="Gas Tight"
                    />
                  </div>
                </div>

                {/* Appliance Safe */}
                <div className="flex items-center gap-4 mb-3">
                  <span className="text-sm text-gray-600">Appliance Safe:</span>
                  <button
                    type="button"
                    onClick={() => updateAppliance(appliance.id, 'applianceSafe', true)}
                    className={`px-4 py-2 rounded-lg text-sm font-medium ${
                      appliance.applianceSafe === true 
                        ? 'bg-green-500 text-white' 
                        : 'bg-gray-100 text-gray-600'
                    }`}
                  >
                    ✓ Yes
                  </button>
                  <button
                    type="button"
                    onClick={() => updateAppliance(appliance.id, 'applianceSafe', false)}
                    className={`px-4 py-2 rounded-lg text-sm font-medium ${
                      appliance.applianceSafe === false 
                        ? 'bg-red-500 text-white' 
                        : 'bg-gray-100 text-gray-600'
                    }`}
                  >
                    ✗ No
                  </button>
                </div>

                {/* Defects */}
                <textarea
                  placeholder="Defects identified (if any)"
                  value={appliance.defectsIdentified}
                  onChange={(e) => updateAppliance(appliance.id, 'defectsIdentified', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900 mb-2"
                  rows={2}
                />
                <textarea
                  placeholder="Remedial action taken/required"
                  value={appliance.remedialAction}
                  onChange={(e) => updateAppliance(appliance.id, 'remedialAction', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm text-gray-900"
                  rows={2}
                />
              </div>
            ))}
          </section>

          {/* Signatures */}
          <section>
            <h2 className="text-sm font-semibold text-gray-500 mb-3">SIGNATURES</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <SignaturePad
                label="Engineer Signature"
                onSignatureChange={setEngineerSignature}
              />
              <SignaturePad
                label="Tenant/Responsible Person Signature"
                onSignatureChange={setTenantSignature}
              />
            </div>
          </section>

          {/* Actions */}
          <div className="flex gap-3 pt-4 border-t">
            <button
              onClick={handleEmail}
              disabled={sending}
              className="flex-1 py-3 bg-blue-600 text-white font-semibold rounded-xl hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {sending ? 'Opening Email...' : sent ? '✓ Email Opened' : '📧 Email to Customer'}
            </button>
          </div>

          {sent && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-3 text-sm text-green-700">
              Email client opened. Please review and send the email.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CP12Form;
