-- BoilerBrain Vector Knowledge Store Schema
-- This schema sets up the necessary tables and extensions for vector similarity search

-- Enable the pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS pgvector;

-- Ensure the UUID extension is available
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create a table to store knowledge embeddings with vector similarity search capability
CREATE TABLE IF NOT EXISTS public.knowledge_embeddings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    content TEXT NOT NULL,                      -- The actual knowledge text
    content_tokens INTEGER,                     -- Token count of the content (for context window planning)
    embedding VECTOR(1536),                     -- OpenAI embedding vector (1536 dimensions)
    metadata JSONB DEFAULT '{}'::jsonb,         -- Flexible metadata for filtering
    tag VARCHAR(100),                           -- Primary classification tag (e.g., 'boiler-maintenance')
    source VARCHAR(255),                        -- Source of the knowledge (e.g., 'user-manual')
    source_url TEXT,                            -- URL of the original source if applicable
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP WITH TIME ZONE,  -- Track usage for potential pruning
    access_count INTEGER DEFAULT 0,             -- Track how often this embedding is used
    relevance_score FLOAT DEFAULT 0.0,          -- Optional manual override for relevance
    is_active BOOLEAN DEFAULT TRUE              -- Flag to temporarily disable entries
);

-- Create a table to log embedding usage for analytics and optimization
CREATE TABLE IF NOT EXISTS public.embedding_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embedding_id UUID REFERENCES public.knowledge_embeddings(id),
    query TEXT NOT NULL,                        -- The original user query
    similarity_score FLOAT,                     -- How similar the query was to this embedding
    session_id VARCHAR(255),                    -- User session for analytics
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create GIN index on the metadata for fast filtering
CREATE INDEX IF NOT EXISTS idx_knowledge_metadata ON public.knowledge_embeddings USING GIN (metadata);

-- Create index on the tag field for fast filtering
CREATE INDEX IF NOT EXISTS idx_knowledge_tag ON public.knowledge_embeddings(tag);

-- Create index on the embedding vector for similarity search
CREATE INDEX IF NOT EXISTS idx_embedding_vector ON public.knowledge_embeddings USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100); -- Adjust lists parameter based on table size

-- Set up function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update the timestamp
CREATE TRIGGER update_knowledge_timestamp
    BEFORE UPDATE ON public.knowledge_embeddings
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- Create function to update access stats
CREATE OR REPLACE FUNCTION update_access_stats()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.last_accessed_at = CURRENT_TIMESTAMP;
    NEW.access_count = OLD.access_count + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update access stats when knowledge is retrieved
CREATE TRIGGER update_knowledge_access
    BEFORE UPDATE ON public.knowledge_embeddings
    FOR EACH ROW
    WHEN (OLD.id = NEW.id AND TG_OP = 'UPDATE')
    EXECUTE FUNCTION update_access_stats();

-- Function to find similar documents
CREATE OR REPLACE FUNCTION find_similar_documents(
    query_embedding VECTOR,
    match_threshold FLOAT,
    match_count INT,
    filter_tag TEXT DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    content TEXT,
    similarity FLOAT,
    tag VARCHAR(100),
    source VARCHAR(255),
    metadata JSONB
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ke.id,
        ke.content,
        1 - (ke.embedding <=> query_embedding) as similarity,
        ke.tag,
        ke.source,
        ke.metadata
    FROM
        public.knowledge_embeddings ke
    WHERE
        ke.is_active = TRUE
        AND (filter_tag IS NULL OR ke.tag = filter_tag)
        AND (1 - (ke.embedding <=> query_embedding)) > match_threshold
    ORDER BY
        ke.embedding <=> query_embedding
    LIMIT match_count;
    
    -- Record access to the selected embeddings
    UPDATE public.knowledge_embeddings
    SET last_accessed_at = CURRENT_TIMESTAMP,
        access_count = access_count + 1
    WHERE id IN (
        SELECT id FROM find_similar_documents
    );
END;
$$;

-- Enable Row Level Security
ALTER TABLE public.knowledge_embeddings ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public read access" ON public.knowledge_embeddings
    FOR SELECT
    USING (is_active = TRUE);

CREATE POLICY "Admin full access" ON public.knowledge_embeddings
    FOR ALL
    USING (auth.role() = 'service_role');

-- Add comment to document the schema
COMMENT ON TABLE public.knowledge_embeddings IS 'Stores knowledge text and their vector embeddings for semantic search in BoilerBrain';
