-- Table to store user feedback
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- Using TEXT to allow 'anonymous' for non-registered users
    message TEXT NOT NULL,
    question_index INTEGER NOT NULL,
    rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS (Row Level Security)
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all users to insert feedback (including anonymous)
CREATE POLICY "Anyone can add feedback" ON public.feedback
    FOR INSERT TO authenticated, anon
    WITH CHECK (true);

-- Create policy to allow admins to view all feedback
CREATE POLICY "Admins can view all feedback" ON public.feedback
    FOR SELECT TO authenticated
    USING (auth.uid() IN (
        SELECT id FROM public.users WHERE tier = 'Admin'
    ));

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON public.feedback
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();
